EXTENDED_ALPHABET = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890_-"
MAX_TESTCASES = 10
ALPHABET = "QWERTYUIOPASDFGHJKLZXCVBNM"
TIMELIMITS = {
        "cpp":1,
        "java":2,
        "python":4,
    }